name: manual_test_pip

on:
  workflow_dispatch

jobs:
  build_win:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.9, "3.10"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: check clone
      run: |
        pwd
        ls
        python -c "import shutil;shutil.rmtree('medspacy')"
        ls

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - run: |
        conda install -c conda-forge libiconv
        conda list
        python --version
        pip install --upgrade pip
        pip install --use-pep517 -r tests_requirements.txt
        python -m spacy download de_core_news_sm
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_md
        # multilingual models for testing compatibility
        python -m spacy download es_core_news_sm
        python -m spacy download pl_core_news_sm
        python -m spacy download de_core_news_sm
        python -m spacy download xx_ent_wiki_sm

    - name: Test with pytest
      run: |        
        pytest

  build_linux_mac:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10.x]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: check clone
      run: |
        pwd
        ls
        python -c "import shutil;shutil.rmtree('medspacy')"
        ls

    - name: Set up Python ${{ matrix.python-version }}  ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}   
        cache: 'pip'   
        cache-dependency-path: 'tests_requirements.txt'
    - run: |
        python --version
        pip install --upgrade pip
        pip install --use-pep517 -r tests_requirements.txt
        python -m spacy download de_core_news_sm
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_md
        # multilingual models for testing compatibility
        python -m spacy download es_core_news_sm
        python -m spacy download pl_core_news_sm
        python -m spacy download de_core_news_sm
        python -m spacy download xx_ent_wiki_sm

    - uses: actions/checkout@v3
    - name: check clone
      run: |
        pwd
        ls
        python -c "import shutil;shutil.rmtree('medspacy')"
        ls

    - name: Test with pytest
      run: |        
        pytest

