name: single_pip_install_test

on:
  workflow_dispatch

jobs:

  test_win_linux_mac:
  
    # TODO: Do we care if this only runs on allowed branches since we check push/pull_request above?
    #if: github.ref == 'refs/heads/master' OR github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: check clone
      run: |
        pwd
        ls
        python -c "import shutil;shutil.rmtree('medspacy')"
        ls

    - name: Set up Python ${{ matrix.python-version }}  ${{ matrix.os }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}   
        cache: 'pip'   
        cache-dependency-path: 'requirements_piptests.txt'
    - run: |
        python --version
        pip install --upgrade pip
        pip install --use-pep517 -r requirements_piptests.txt
        

    - name: Test with pytest
      run: |
        pwd
        ls
        python -c "import nltk"
        python -c "import pandas"
        python -c "import spacy"
        python -c "import medspacy"
